### ISSUE TITLE
Problem in generating Spark program

### ISSUE THREAD

**Issue by KamishiroArisu** [dbtoaster/dbtoaster-backend#103]
Hi,
I have a problem in generating Spark program.

When I run 'bin/dbtoaster -O3 -l spark --batch -o rst.scala examples/queries/simple/rst.sql' ,
I get the following messages:
java.lang.Exception: [Ljava.lang.String;@71423665 failed because:
Fatal error: exception Failure("Partitioning information not found for T")

The README says that 'The current implementation can compile the provided TPCH-like queries into executable Spark programs.'

I would like to ask if dbtoaster currently supports generating Spark programs for queries like rst.sql? If not at the moment, is there any plan to support it in later versions?

**Comment by losmi83** [comment]
Yes, you can run queries over non-tpch schemas using the Spark backend; the entire process is not entirely automatic though. 

1) Pull the latest version of the [frontend](https://github.com/dbtoaster/dbtoaster-a5) and recompile: 
`make clean && make`

2) You can find the partitioning information for the TPC-H and simple datasets in [src/global/Partitioner.ml](https://github.com/dbtoaster/dbtoaster-a5/blob/ccaafbaa85a27aa32e6f209476e35c5d1a4f9f1b/src/global/Partitioner.ml#L53):

3) Add the partitioning information for your datasets to this function and recompile.

4) Pull the latest version of the backend (this repo). You should be able to generate Spark code.

**Comment by KamishiroArisu** [comment]
Thank you very much.

I managed to get rst up and run on spark using the above approach.

But when I try to generate the Spark program for the following sql
CREATE STREAM Graph(src int, dst int)
  FROM FILE 'examples/data/simple/graph.dat' LINE DELIMITED csv;

SELECT A.src, A.dst, C.src, C.dst
FROM Graph AS A, Graph AS B, Graph AS C
WHERE A.dst = B.src AND B.dst = C.src;


I encountered this exception
[info] Running ddbt.Compiler -l spark --batch -O3 /path/to/get_path2.sql -o /path/to/get_path2.scala
[error] java.lang.RuntimeException: Transformation not implemented yet
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at ddbt.codegen.DistributedM3Gen$Statement$.createRepartition(DistributedM3Gen.scala:216)
[error]         at ddbt.codegen.DistributedM3Gen.prepareExpression(DistributedM3Gen.scala:661)
[error]         at ddbt.codegen.DistributedM3Gen.prepareExpression(DistributedM3Gen.scala:612)
[error]         at ddbt.codegen.DistributedM3Gen.prepareExpression(DistributedM3Gen.scala:669)
[error]         at ddbt.codegen.DistributedM3Gen.prepareStatement(DistributedM3Gen.scala:548)
[error]         at ddbt.codegen.LMSSparkGen$$anonfun$2$$anonfun$apply$5.apply(SparkGen.scala:68)
[error]         at ddbt.codegen.LMSSparkGen$$anonfun$2$$anonfun$apply$5.apply(SparkGen.scala:68)
[error]         at scala.collection.immutable.List.flatMap(List.scala:327)
[error]         at ddbt.codegen.LMSSparkGen$$anonfun$2.apply(SparkGen.scala:68)
[error]         at ddbt.codegen.LMSSparkGen$$anonfun$2.apply(SparkGen.scala:67)
[error]         at scala.collection.immutable.List.flatMap(List.scala:327)
[error]         at ddbt.codegen.LMSSparkGen.apply(SparkGen.scala:67)
[error]         at ddbt.Compiler$.codegen(Compiler.scala:400)
[error]         at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:625)
[error]         at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:625)
[error]         at ddbt.lib.Utils$.ns(Utils.scala:40)
[error]         at ddbt.Compiler$.compile(Compiler.scala:625)
[error]         at ddbt.Compiler$.main(Compiler.scala:680)
[error]         at ddbt.Compiler.main(Compiler.scala)



I can only work around it by the following sql
CREATE STREAM Graph1(src int, dst int)
  FROM FILE 'examples/data/simple/graph.dat' LINE DELIMITED csv;

CREATE STREAM Graph2(src int, dst int)
  FROM FILE 'examples/data/simple/graph.dat' LINE DELIMITED csv;

CREATE STREAM Graph3(src int, dst int)
  FROM FILE 'examples/data/simple/graph.dat' LINE DELIMITED csv;

SELECT A.src, A.dst, C.src, C.dst
FROM Graph1 AS A, Graph2 AS B, Graph3 AS C
WHERE A.dst = B.src AND B.dst = C.src;

**Comment by losmi83** [comment]
Glad to hear you were able to run rst. 

The support for self-joins was not implemented in the spark code generator due to lack of time; all other parts of DBToaster can handle self-joins. Go with the suggested workaround, making sure that every update is replicated to all three relations.

**Comment by KamishiroArisu** [comment]
Thank you very much.

I have one last question. Regarding the partitioning info that needs to be set up, is it an estimate of how many partitions the data in my streams can be divided into by the fields(like COUNT DISTINCT)?

**Comment by losmi83** [comment]
1. Yes, you provide an estimated number of distinct values for each attribute the result might be partitioned on (these are usually join attributes). The optimizer will estimate the cardinality of intermediate views and for each view, choose the attribute with the max cardinality as the partitioning attribute for that view.

2. You are generating code for single-tuple inserts/deletes, while only batch updates are meaningful to support on Spark, so you need to add '--batch' to the above command. Within a batch of updates, you can have inserts and deletions. 

The schema of an input file containing both inserts and deletes contains two additional fields: 
* orderID - defines the order of inserts/deletes for the entire dataset; could be 0 for all if you do not care about the order
* eventID - 0 for delete, 1 for insert 
See example datasets from our [data repository](https://github.com/dbtoaster/dbtoaster-experiments-data/tree/master/tpch/standard_del).

You probably need to pass '-d <dataset_name>' when compiling the query. Also, the dataset name must end with "_del" if you want it to be recognized as a mixed dataset.

**Comment by KamishiroArisu** [comment]
Thank you very much.

I have managed to generate my spark program. However, the following code snippet in the generated program has a type mismatch problem.
...
// Dequeue next batch
      val rddPipe1 = ctx.rdd.mapPartitions(_.toList.map { case (id, localCtx) =>
          localCtx.DELTA_GRAPH1 = localCtx.DELTA_GRAPH1_QUEUE.dequeue
          localCtx.DELTA_GRAPH2 = localCtx.DELTA_GRAPH2_QUEUE.dequeue
          localCtx.DELTA_GRAPH3 = localCtx.DELTA_GRAPH3_QUEUE.dequeue
      
        (id, localCtx)
      }.iterator, true)
...


In the generated Get_pathLocalMapContext, DELTA_GRAPH1 has type Array[SEntry3_x33_LLL]. However, DELTA_GRAPH1_QUEUE has type mutable.Queue[ArrayBuffer[SEntry3_x33_LLL]].

I add the toArray conversions manually and now the program runs correctly. Maybe I need to add an implicit conversion myself?

**Comment by losmi83** [comment]
I don't recall having this problem. Perhaps just doing the explicit conversion would be the easiest solution.

**Comment by KamishiroArisu** [comment]
Thank you very much. 
My program works fine now.
