### ISSUE TITLE
trouble in dealing with C++ API

### ISSUE THREAD

**Issue by KamishiroArisu** [dbtoaster/dbtoaster-backend#104]
I successfully generated a cpp file by the command sbt "toast -l cpp -O3 --batch -d my_data_set -o my_code.cpp /path/to/my_query.sql"

but I don't know how to compile it into an executable file. It seems that the doc on https://dbtoaster.github.io/docs_cpp.html is not corresponding to the latest implementation. For example, the generated code doesn't have the class Program.

I checked the files under release/lib/dbt_c++, so I tried the following command:
g++-11 -o my_app -I /path/to/dbt_c++/lib/ -I /path/to/dbt_c++/driver /path/to/dbt_c++/driver/main.cpp my_code.cpp

but it throws a bunch of errors like: 
/xxx/lib/dbt_c++/driver/utils.hpp: In function 'T convert(const string&) [with T = dbtoaster::DateType; std::string = std::__cxx11::basic_string<char>]':
/xxx/lib/dbt_c++/driver/utils.hpp:45:21: error: 'dbtoaster::DateFormat' has not been declared
   45 |   return dbtoaster::DateFormat::parse(s.c_str());
......

what is the correct way of building an executable file from the generated source code? I need to build from the source code because I may make some slight modifications to it in the future.

Thank you!

**Comment by losmi83** [comment]
You can compile as follows:

g++ -O3 -std=c++14 -I ddbtoaster/srccpp/lib -I ddbtoaster/srccpp/driver ddbtoaster/srccpp/driver/main.cpp -include <generated_hpp_file> -o <output_file> 

The website refers to the old c++ runtime.

**Comment by bdaiab** [comment]
Thank you for your reply.

It now throws the following error:
error: no matching member function for call to 'addSource'
      visitor.template addSource(
      ~~~~~~~~~~~~~~~~~^~~~~~~~~
ddbtoaster/release/lib/dbt_c++/driver/application.hpp:165:24: note: in instantiation of function template specialization
      'dbtoaster::data_t::registerSources<Application::Visitor>' requested here
    dbtoaster::data_t::registerSources(visitor);
                       ^
ddbtoaster/release/lib/dbt_c++/driver/application.hpp:52:10: note: candidate function template not viable: requires 3 arguments, but 5 were provided
    void addSource(string type, FileSource source, Adaptor adaptor) {
         ^
ddbtoaster/release/lib/dbt_c++/driver/application.hpp:67:10: note: candidate function template not viable: requires 4 arguments, but 5 were provided
    void addSource(string type, FileSource source, Adaptor1 adaptor1, Adaptor2 adaptor2) {
         ^
1 error generated.


The data file is the same for 3 streams in my DDL. So the generated hpp file has the following code snippet which corresponds to the error above:
template <class Visitor>
    static void registerSources(Visitor& visitor) {
      visitor.template addSource(
        "CSV",
        FileSource("xxx/graph.dat"),
        Graph1Adaptor{},
        Graph2Adaptor{},
        Graph3Adaptor{}
      );
    }

Is it a problem? Do I need to make three copies of my data file and match one to each stream?

Thank you!

**Comment by losmi83** [comment]
No need to create multiple streams if they share the same source file. Self-joins are supported so you could write simply as:

CREATE STREAM R(A int, B int) FROM FILE 'graph.dat' LINE DELIMITED CSV ();
SELECT * FROM R r1, R r2, R r3;

Alternatively, you can create one stream for each copy of the input file.

**Comment by bdaiab** [comment]
Thank you for your reply.

I tried to use the command 'toast -l cpp -O3 --batch -o my_code2.hpp /path/to/my_query2.sql' and it threw the following exception.

[info] Running ddbt.Compiler -l cpp -O3 --batch -o my_code2.hpp /path/to/my_query2.sql
[error] java.lang.RuntimeException: Delta relation requires secondary indices. Turn on old runtime library (-xruntime).
[error]         at scala.sys.package$.error(package.scala:27)
[error]         at ddbt.codegen.ICppGen$class.ddbt$codegen$ICppGen$$cpsExpr(CppGen.scala:1309)
[error]         at ddbt.codegen.ICppGen$$anonfun$ddbt$codegen$ICppGen$$cpsExpr$11.apply(CppGen.scala:1426)
[error]         at ddbt.codegen.ICppGen$$anonfun$ddbt$codegen$ICppGen$$cpsExpr$11.apply(CppGen.scala:1424)
[error]         at ddbt.codegen.ICppGen$class.ddbt$codegen$ICppGen$$cpsExpr(CppGen.scala:1297)
[error]         at ddbt.codegen.ICppGen$$anonfun$ddbt$codegen$ICppGen$$cpsExpr$11.apply(CppGen.scala:1426)
[error]         at ddbt.codegen.ICppGen$$anonfun$ddbt$codegen$ICppGen$$cpsExpr$11.apply(CppGen.scala:1424)
[error]         at ddbt.codegen.ICppGen$class.ddbt$codegen$ICppGen$$cpsExpr(CppGen.scala:1297)
[error]         at ddbt.codegen.ICppGen$class.ddbt$codegen$ICppGen$$emitStmt(CppGen.scala:289)
[error]         at ddbt.codegen.ICppGen$$anonfun$25.apply(CppGen.scala:341)
[error]         at ddbt.codegen.ICppGen$$anonfun$25.apply(CppGen.scala:341)
[error]         at scala.collection.immutable.List.map(List.scala:272)
[error]         at ddbt.codegen.ICppGen$class.ddbt$codegen$ICppGen$$emitTrigger(CppGen.scala:341)
[error]         at ddbt.codegen.ICppGen$$anonfun$emitStreamTriggers$1.apply(CppGen.scala:449)
[error]         at ddbt.codegen.ICppGen$$anonfun$emitStreamTriggers$1.apply(CppGen.scala:448)
[error]         at scala.collection.immutable.List.map(List.scala:272)
[error]         at ddbt.codegen.ICppGen$class.emitStreamTriggers(CppGen.scala:448)
[error]         at ddbt.codegen.CppGen.emitStreamTriggers(CppGen.scala:13)
[error]         at ddbt.codegen.ICppGen$class.emitTriggerFunctions(CppGen.scala:458)
[error]         at ddbt.codegen.ICppGen$class.emitIVMStructure(CppGen.scala:894)
[error]         at ddbt.codegen.ICppGen$class.apply(CppGen.scala:1537)
[error]         at ddbt.codegen.CppGen.apply(CppGen.scala:13)
[error]         at ddbt.Compiler$.codegen(Compiler.scala:401)
[error]         at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:626)
[error]         at ddbt.Compiler$$anonfun$3.apply(Compiler.scala:626)
[error]         at ddbt.lib.Utils$.ns(Utils.scala:40)
[error]         at ddbt.Compiler$.compile(Compiler.scala:626)
[error]         at ddbt.Compiler$.main(Compiler.scala:685)
[error]         at ddbt.Compiler.main(Compiler.scala)

Anyway, I used three streams to read three copied files to meet my requirements.
Thank you for your help!
