### ISSUE TITLE
Error in parsing M3 generated for TPCH-1 by alpha6

### ISSUE THREAD

**Issue by mdashti** [dbtoaster/dbtoaster-backend#41]
There is a compile error for the code generated by alpha6 frontend.
By running:

unit  -x -xsc -xvm -nocache -l scala -w 0 -s 3 -csv bench-all.csv -dump bench-all-dump.txt -p 2  -q tpch.*query1 -d big_del

You get:

[error] Exception in thread "main" java.lang.RuntimeException: [22.43] failure: Expected ')'
[error] 
[error](%28__sql_inline_agg_1 ^= %28%28-INTERVAL) +
[error] 
[error]                                           ^
[error]     at scala.sys.package$.error(package.scala:27)
[error]     at ddbt.frontend.M3Parser$.apply(Parsers.scala:124)
[error]     at ddbt.frontend.M3Parser$.apply(Parsers.scala:76)
[error]     at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
[error]     at ddbt.Compiler$.compile(Compiler.scala:128)
[error]     at ddbt.UnitTest$$anonfun$genQueryScala$1.apply$mcV$sp(UnitTest.scala:237)
[error]     at ddbt.UnitTest$Printer.run(UnitTest.scala:397)
[error]     at ddbt.UnitTest$.genQueryScala(UnitTest.scala:237)
[error]     at ddbt.UnitTest$$anonfun$main$4$$anonfun$apply$8.apply(UnitTest.scala:148)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:145)
[error]     at ddbt.UnitTest$$anonfun$main$4.apply(UnitTest.scala:131)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
[error]     at ddbt.UnitTest$.main(UnitTest.scala:131)
[error]     at ddbt.UnitTest.main(UnitTest.scala)

**Comment by losmi83** [comment]
alpha6 abandoned
