### ISSUE TITLE
TPCH-7 and TPCH-15 timeout

### ISSUE THREAD

**Issue by 4tXJ7f** [dbtoaster/dbtoaster-backend#70]
https://gist.github.com/4tXJ7f/01fecafe2c4888f81992

**Comment by losmi83** [comment]
Not an issue. TPCH-15 is recomputed upon each update, thus it has terrible performance. TPCH-7 is a cyclic query and materializes large maps (one can use the flag HEURISTICS-DECOMPOSE-OVER-TABLES to avoid them).
