### ISSUE TITLE
Incorrect result for TPCH-19, TPCH-17, TPCH-17a and TPCH-8 on BigDel dataset with -O3

### ISSUE THREAD

**Issue by mdashti** [dbtoaster/dbtoaster-backend#76]
This is the output for TPCH-17:

[error] Exception in thread "main" java.lang.Exception: Bad value: 7017.722857135836 (expected 4905.0542857142855)

The problem was there even in the previous release of DBToaster.

To see the error in the new backend, run this command in SBT:
  unit -no-cache -v -x -xsc -xvm -p 2 -w 0 -s 1 -t 30000 -csv bench-all.csv -dump bench-all-dump.txt -l lscala -d big_del -q tpch.*query(8|(17)|(17a)|(19)) -O3

And for the old backend:
  cd scripts/test
  ./query_test.rb -t scala --dataset big_del tpch19
  ./query_test.rb -t scala --dataset big_del tpch17
  ./query_test.rb -t scala --dataset big_del tpch17a
  ./query_test.rb -t scala --dataset big_del tpch8

The reason behind this bug being hidden until now is the fact that all validation tests were only checking for the default parameters to DBToaster, which by default triggers -O2 and not -O3 optimization level.

With high probability, it should be a front-end bug, which generates incorrect M3 programs upon using -O3 optimizations for TPCH-19, TPCH-17, TPCH-17a and TPCH-8.

**Comment by losmi83** [comment]
Not appearing anymore.
